namespace BotReborn.Model {
    public enum ElementType {
        Text = 0,
        Image,
        Face,
        At,
        Reply,
        Service,
        Forward,
        File,
        Voice,
        Video,
        LightApp,
        RedBag,
        //这是群礼物
        HoldingYourHand = 280,
        CuteCat = 281,
        MysteryMask = 284,
        SweetWink = 285,
        ImBusy = 286,
        HappyCola = 289,
        LuckyBracelet = 290,
        Cappuccino = 299,
        CatWatch = 302,
        FleeceGloves = 307,
        RainbowCandy = 308,
        LoveMask = 312,
        Stronger = 313,
        LoveMicrophone = 367,
    }
}